SELECT EMPLOYE.NO, EMPLOYE.NOM,
       GROUP_CONCAT(DISTINCT PROJET.NOM SEPARATOR " et ") AS CHEF_DE ,
       GROUP_CONCAT(DISTINCT TACHE.PROJET SEPARATOR " et ") AS EMPLOYE_POUR,
       GROUP_CONCAT(DISTINCT EVALUATION.PROJET SEPARATOR " et ") AS EXPERT_POUR
FROM EMPLOYE LEFT JOIN TACHE ON EMPLOYE.NO = TACHE.EMPLOYE
             LEFT JOIN PROJET ON EMPLOYE.NO = PROJET.CHEF
             LEFT JOIN EVALUATION ON EMPLOYE.NO = EVALUATION.EXPERT
WHERE (SELECT COUNT(DISTINCT PROJET.NOM) FROM PROJET) = (SELECT COUNT(DISTINCT PROJET.NOM) GROUP BY EMPLOYE.NO)+
                                                        (SELECT COUNT(DISTINCT TACHE.PROJET) GROUP BY EMPLOYE.NO)+
                                                        (SELECT COUNT(DISTINCT EVALUATION.PROJET) GROUP BY EMPLOYE.NO)
GROUP BY EMPLOYE.NO
